### ISSUE TITLE
Excluding shortcodes (going further : excluding regex) ?

### ISSUE THREAD

**Issue by borisschapira** [jolicode/JoliTypo#14]
Hi,

I'm applying JoliTypo on Wordpress contents but sometimes, these contents contains shortcodes like ```[[ poney ]]```. Is there a way to tell Jolitypo not to replace content inside these shortcodes, like a Regex Exclusion Pattern for example ?

**Comment by damienalexandre** [comment]
Hey! Sorry for the late answer,
there is no way to catch tags that are not HTML one's, and I have no plan to introduce this feature.

This is mainly because JoliTypo is based on libxml for parsing and so works only with HTML. We have a list of protected tags we never edit that you can customize:

```
$fixer->setProtectedTags(array('pre', 'a')); // Never edit links and pre content
```

JoliTypo is designed to work on HTML, and results from markdown or any other formats are not tested / will be random and unexpected. So you should just call the fixer _after_ Wordpress did all the transformations.

I'm closing this issue but we can still talk about it :)
